---
abstract: TODO
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  File::Slurp: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 1.02
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-XMLNorm
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.05
  Error::Pure: 0.15
  PYX: 0.01
  PYX::Parser: 0.01
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=PYX-XMLNorm
  homepage: https://github.com/tupinek/PYX-XMLNorm
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/PYX-XMLNorm
version: 0.01
